version: '3.8'
services:
  nocodb:
    depends_on:
      db:
        condition: service_healthy
    image: 'nocodb/nocodb:latest'
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8000:8000
  db:
    image: postgres:14
    container_name: lab-db
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${API_DB_USER}
      - POSTGRES_PASSWORD=${API_DB_PASS}
      - POSTGRES_DB=${API_DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${API_DB_USER} -d ${API_DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5435:5432
networks:
  app_network:
    driver: bridge
